; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Mar 11 2023 15:28:49 GMT+0100 (hora estándar de Europa central)
; ================================================================================

DATALDWKKVGC8B:
	dc.w DATALDWKKVGC8B_0-DATALDWKKVGC8B, DATALDWKKVGC8B_1-DATALDWKKVGC8B
	dc.w DATALDWKKVGC8B_2-DATALDWKKVGC8B
DATALDWKKVGC8B_0: dc.b $1
	dc.b $F4, $6, $0, $6, $F8
DATALDWKKVGC8B_1: dc.b $1
	dc.b $F4, $6, $0, $C, $F8
DATALDWKKVGC8B_2: dc.b $1
	dc.b $F4, $6, $0, $0, $F8
	even