; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Mar 11 2023 15:32:19 GMT+0100 (hora estándar de Europa central)
; ================================================================================

DATA5325L45B7MS:
	dc.w DATA5325L45B7MS_0-DATA5325L45B7MS, DATA5325L45B7MS_1-DATA5325L45B7MS
	dc.w DATA5325L45B7MS_2-DATA5325L45B7MS
DATA5325L45B7MS_0: dc.b $1
	dc.b $FC, $5, $0, $6, $F8
DATA5325L45B7MS_1: dc.b $1
	dc.b $FC, $5, $0, $A, $F8
DATA5325L45B7MS_2: dc.b $1
	dc.b $F4, $6, $0, $0, $F8
	even