; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Mar 11 2023 15:30:39 GMT+0100 (hora estándar de Europa central)
; ================================================================================

DATABPYRVON8AY:
	dc.w DATABPYRVON8AY_0-DATABPYRVON8AY, DATABPYRVON8AY_1-DATABPYRVON8AY
	dc.w DATABPYRVON8AY_2-DATABPYRVON8AY
DATABPYRVON8AY_0: dc.b $1
	dc.b $FC, $9, $0, $6, $F4
DATABPYRVON8AY_1: dc.b $1
	dc.b $FC, $9, $0, $C, $F4
DATABPYRVON8AY_2: dc.b $1
	dc.b $F4, $6, $0, $0, $F8
	even