; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Dec 27 2022 23:44:18 GMT+0100 (hora estándar de Europa central)
; ================================================================================

MapGlassBlock:
	dc.w MapGlassBlock_0-MapGlassBlock, MapGlassBlock_1-MapGlassBlock
	dc.w MapGlassBlock_2-MapGlassBlock, MapGlassBlock_3-MapGlassBlock
MapGlassBlock_0: dc.b $6
	dc.b $DC, $C, $0, $0, $E0
	dc.b $DC, $C, $8, $0, $0
	dc.b $E4, $F, $0, $4, $E0
	dc.b $E4, $F, $8, $4, $0
	dc.b $4, $F, $0, $4, $E0
	dc.b $4, $F, $8, $4, $0
MapGlassBlock_1: dc.b $6
	dc.b $DC, $F, $0, $4, $E0
	dc.b $DC, $F, $8, $4, $0
	dc.b $FC, $F, $0, $4, $E0
	dc.b $FC, $F, $8, $4, $0
	dc.b $1C, $C, $0, $0, $E0
	dc.b $1C, $C, $8, $0, $0
MapGlassBlock_2: dc.b $2
	dc.b $8, $6, $0, $14, $F0
	dc.b $0, $6, $0, $14, $0
MapGlassBlock_3: dc.b $A
	dc.b $C8, $C, $0, $0, $E0
	dc.b $C8, $C, $8, $0, $0
	dc.b $D0, $F, $0, $4, $E0
	dc.b $D0, $F, $8, $4, $0
	dc.b $F0, $F, $0, $4, $E0
	dc.b $F0, $F, $8, $4, $0
	dc.b $10, $F, $0, $4, $E0
	dc.b $10, $F, $8, $4, $0
	dc.b $30, $C, $0, $0, $E0
	dc.b $30, $C, $8, $0, $0
	even