; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Mar 11 2023 19:15:43 GMT+0100 (hora estándar de Europa central)
; ================================================================================

MapSignpost:
	dc.w MapSignpost_0-MapSignpost, MapSignpost_1-MapSignpost
	dc.w MapSignpost_2-MapSignpost, MapSignpost_3-MapSignpost
	dc.w MapSignpost_4-MapSignpost
MapSignpost_0: dc.b $3
	dc.b $F0, $B, $0, $0, $E8
	dc.b $F0, $B, $8, $0, $0
	dc.b $10, $1, $0, $38, $FC
MapSignpost_1: dc.b $2
	dc.b $F0, $F, $0, $C, $F0
	dc.b $10, $1, $0, $38, $FC
MapSignpost_2: dc.b $2
	dc.b $F0, $3, $0, $1C, $FC
	dc.b $10, $1, $8, $38, $FC
MapSignpost_3: dc.b $2
	dc.b $F0, $F, $8, $C, $F0
	dc.b $10, $1, $8, $38, $FC
MapSignpost_4: dc.b $3
	dc.b $F0, $B, $0, $20, $E8
	dc.b $F0, $B, $0, $2C, $0
	dc.b $10, $1, $0, $38, $FC
	even