; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Dec 24 2022 19:16:19 GMT+0100 (hora estándar de Europa central)
; ================================================================================

DATAIGVPWSOAGPG:
	dc.w DATAIGVPWSOAGPG_0-DATAIGVPWSOAGPG, DATAIGVPWSOAGPG_1-DATAIGVPWSOAGPG
	dc.w DATAIGVPWSOAGPG_2-DATAIGVPWSOAGPG, DATAIGVPWSOAGPG_3-DATAIGVPWSOAGPG
	dc.w DATAIGVPWSOAGPG_4-DATAIGVPWSOAGPG, DATAIGVPWSOAGPG_5-DATAIGVPWSOAGPG
DATAIGVPWSOAGPG_0: dc.b $1
	dc.b $F0, $7, $40, $0, $F8
DATAIGVPWSOAGPG_1: dc.b $1
	dc.b $F0, $7, $40, $8, $F8
DATAIGVPWSOAGPG_2: dc.b $1
	dc.b $F0, $7, $40, $10, $F8
DATAIGVPWSOAGPG_3: dc.b $1
	dc.b $F0, $7, $40, $18, $F8
DATAIGVPWSOAGPG_4: dc.b $1
	dc.b $F0, $7, $40, $20, $F8
DATAIGVPWSOAGPG_5: dc.b $1
	dc.b $F0, $7, $40, $28, $F8
	even